* Generelle notater
kultur bygd opp av appearance conversations, peer appearance criticism (or teasing), exposure to appearance-focused media. 
* forskningspørsmål

* resultater
- utseende er veldig viktig i skolen
- å være attraktiv beror seg på å være tynn, sjeldent noe annet som ansikt osv.
- fashion magasiner kilde for hvordan de ville se ut, ungene tror noe av problemet med spiseforstyrrleser osv. kommer derfra
- største presset kom gjennom dieter, mange så på dette som normalt
- diett er en gruppeting, noe for å passe inn. Skaper et gruppepress
- forskjell i hvor mye de valuer utseende i forskjellige grupper
- må være en viss type utseende for å bli med i gruppe, må også vise commitment (gruppe dieting)
- gossip om vekt, så dette var public informasjon. Ikke sett som rart for noen av jentene. Dette tillater "weight surveillance", og en konstant tanke om at ens vekt blir overvåket
- mange satt sunt = tynn
- ordet sunt var et cover for å skulle passe vekt osv.
- skole hadde masse for å hjelpe mot dette, men for mye fokus på det syke
