* immersion
Det var en altoppslukende jobb.
En jobb som river deg vekk fra et vanlig liv, men desto letter å skulle skape et liv sammen med andre barfolk
Ble fort til mye drikking etter jobb, en type stigma av å ikke bli igjen og drikke.
Alltid noen andre barfolk av samtidig som deg, så blir en enda mer "immersive" livsstil.
Mange eksempeler på hvordan drikking rett og slett ble en del av normen, og det var så lett, og så greie rutiner på det at det skjedde automatisk
I mange ekstremer ville drikking være en coping mecahnism (drikk så mange som mulig på jobb for å holde ut, drikk så mye som mulig etter jobb for å holde ut)b
Fysisk og psykisk utmattelse var stor del av jobben, sammen med mye stress til tider.   
Det meste var hakket mer intenst på superbarene (større barer med større interconnected deler)

* distancing
** moving on  
   Mange av arbeiderne begynner ettehvert å distansere seg fra jobben. Som i at det bare er en midlertidig jobb f.eks.
   Begynner å distansere seg dess eldre man blir.
** an unsustainable lifestyle 
   - dårlig matvaner
   - altfor mye drikking
   - endte opp med distanseringg pga. sakte realisering av den dårlig livsstilen med tanke på stress og overflode av annet
